import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { WebSocketProvider } from "@/context/WebSocketContext";
import { ModalProvider } from "@/context/ModalContext";
import { Modal } from "@/components/shared";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pickeeper",
  description: "Generated by us :)",
  icons: {
    icon: "images/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const nextAuthSession = await getServerSession(authOptions);
  return (
    <NextAuthProvider session={nextAuthSession}>
      <WebSocketProvider>
        <ModalProvider>
          <html lang="en">
            <Modal />
            <body className={inter.className}>{children}</body>
          </html>
        </ModalProvider>
      </WebSocketProvider>
    </NextAuthProvider>
  );
}
