database:
  postgres:
    dsn: ""
  mongodb:
    dsn: ""

secretKey: ""

administrator_secretKey: "p%h198~34#Or"

administrator_ip: []

oauth2_google:
  client_id: ""
  client_secret: ""
  redirect_url: ""
