basePath: /
definitions:
  model.JSONErrorResult:
    properties:
      error: {}
      status:
        example: failed
        type: string
    type: object
  model.JSONSuccessResult:
    properties:
      data: {}
      status:
        example: success
        type: string
    type: object
  model.LoginCredentials:
    properties:
      email:
        example: test@mail.com
        type: string
      password:
        example: abc123
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the back-end documentation of the pic-keeper project
  license:
    name: Apache 2.0
  title: Pic-keeper APIs
  version: "1.0"
paths:
  /authen/v1/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: email and password of the user
        in: body
        name: Credentials
        required: true
        schema:
          $ref: '#/definitions/model.LoginCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: The token will be returned inside the data field
          schema:
            allOf:
            - $ref: '#/definitions/model.JSONSuccessResult'
            - properties:
                data:
                  type: object
                status:
                  type: string
              type: object
        "400":
          description: Incorrect input
          schema:
            allOf:
            - $ref: '#/definitions/model.JSONErrorResult'
            - properties:
                error:
                  type: object
                status:
                  type: string
              type: object
        "404":
          description: User does not exist
          schema:
            allOf:
            - $ref: '#/definitions/model.JSONErrorResult'
            - properties:
                error:
                  type: object
                status:
                  type: string
              type: object
        "500":
          description: Unhandled internal server error
          schema:
            allOf:
            - $ref: '#/definitions/model.JSONErrorResult'
            - properties:
                error:
                  type: object
                status:
                  type: string
              type: object
      summary: Login via email and password
      tags:
      - authen
swagger: "2.0"
